DROP FUNCTION IF EXISTS userFunc;
DELIMITER $$
CREATE FUNCTION userFunc(a INT, b INT)
	RETURNS INT
BEGIN
	RETURN a + b;
END $$
DELIMITER ;

SELECT userFunc(1, 3);


DROP FUNCTION IF EXISTS getAgeFunc;
DELIMITER $$
CREATE FUNCTION getAgeFunc(bYear INT)
	RETURNS INT
BEGIN
	RETURN YEAR(CURDATE()) - bYear;
END $$
DELIMITER ;

SELECT getAgeFunc(1994);